[env]
NODE_ENV = 'development'
_.python.venv = "/workspace/.venv"

[tools]
julia = '1.10.5'
node = '22.9.0'
pandoc = '3.4'
python = "3.12.7"
r = '4.4.1'
rust = '1.81.0'
rye = '0.41.0'

[plugins]
julia = 'https://github.com/rkyleg/asdf-julia.git'
pandoc = 'https://github.com/Fbrisset/asdf-pandoc.git'
r = 'https://github.com/asdf-community/asdf-r.git'
rye = 'https://github.com/Azuki-bar/asdf-rye'

[settings]
verbose = false
yes = false
