[env]
NODE_ENV = 'development'
_.python.venv = "/workspace/.venv"

[tools]
julia = "1.11.2"
node = "23.3.0"
pandoc = '3.5'
python = "3.13.0"
r = '4.4.2'
rust = "1.83.0"
rye = '0.42.0'

[alias]
julia = 'https://github.com/rkyleg/asdf-julia.git'
pandoc = 'https://github.com/Fbrisset/asdf-pandoc.git'
r = 'https://github.com/asdf-community/asdf-r.git'
rye = 'https://github.com/Azuki-bar/asdf-rye'

[settings]
verbose = false
yes = false
