[env]
NODE_ENV = 'development'
_.python.venv = "/workspace/.venv"

[tools]
julia = "latest"
bun = "latest"
python = "3.13"
r = "latest"
rust = "latest"
uv = "latest"

[settings]
verbose = false
yes = false
