[env]
NODE_ENV = 'development'
_.python.venv = "/workspace/.venv"

[tools]
julia = "1.11.5"
node = "24.0.2"
python = "3.13.3"
r = "4.5.0"
rust = "1.87.0"
rye = "0.44.0"

[alias]
julia = 'https://github.com/rkyleg/asdf-julia.git'
r = 'https://github.com/asdf-community/asdf-r.git'
rye = 'https://github.com/Azuki-bar/asdf-rye'

[settings]
verbose = false
yes = false
