[env]
NODE_ENV = 'development'
_.python.venv = "/workspace/.venv"

[tools]
julia = '1.10.3'
node = '22.2.0'
pandoc = '3.2'
python = '3.12.3'
r = '4.4.0'
rust = '1.78.0'
rye = '0.34.0'

[plugins]
julia = 'https://github.com/rkyleg/asdf-julia.git'
pandoc = 'https://github.com/Fbrisset/asdf-pandoc.git'
r = 'https://github.com/asdf-community/asdf-r.git'
rye = 'https://github.com/Azuki-bar/asdf-rye'

[settings]
verbose = false
yes = false
