[project]
name = "playground"
version = "0.1.0"
description = "Playground"
authors = [{ name = "Shoichieo Odaka", email = "odakas1994@gmail.com" }]
readme = "README.md"
requires-python = ">= 3.11"
dependencies = [
    "jupyter>=1.0.0",
    "matplotlib>=3.8.0",
    "notebook>=7.0.3",
    "numpy>=1.26.0",
    "pandas>=2.0.3",
    "pandas-stubs>=2.0.3.230814",
    "scikit-learn>=1.3.0",
    "scipy>=1.11.2",
    "seaborn>=0.12.2",
    "statsmodels>=0.14.0",
    "sympy>=1.12",
    "torch>=2.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true

[tool.hatch.metadata]
allow-direct-references = true
