[project]
name = "playground"
version = "0.1.0"
description = "Playground"
authors = [{ name = "Shoichieo Odaka", email = "odakas1994@gmail.com" }]
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
    "jupyter>=1.0.0",
    "matplotlib>=3.8.3",
    "matplotlib-fontja>=1.0.0",
    "mecab-python3>=1.0.8",
    "notebook>=7.1.1",
    "numpy>=1.26.4",
    "openpyxl>=3.1.2",
    "pandas==2.2.0",
    "pandas-stubs==2.2.0.240218",
    "pyper>=1.1.2",
    "scikit-learn>=1.4.1.post1",
    "scipy>=1.12.0",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.1",
    "sympy>=1.12",
    "tensorflow>=2.16.1",
    "torch>=2.2.1",
    "unidic-lite>=1.0.8",
    "xarray>=2024.2.0",
    "pyarrow>=15.0.1",
]

[project.scripts]
hello = "workspace:playground"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/workspace"]
