[project]
name = "playground"
version = "0.1.0"
description = "Playground"
authors = [{ name = "Shoichieo Odaka", email = "odakas1994@gmail.com" }]
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
    "arch>=7.0.0",
    "armagarch>=1.0.4",
    "black>=24.4.2",
    "functime>=0.9.5",
    "huggingface-hub>=0.23.4",
    "ipyvuetable>=0.3.0",
    "jax>=0.4.30",
    "jupyter>=1.0.0",
    "jupyterlab-code-formatter>=2.2.1",
    "jupyterlab-language-pack-ja-jp>=4.2.post1",
    "jupyterlab-lsp>=5.1.0",
    "lightgbm>=4.4.0",
    "matplotlib-fontja>=1.0.0",
    "matplotlib>=3.9.1",
    "mecab-python3>=1.0.8",
    "mgarch>=0.3.0",
    "mvgarch>=1.0.1",
    "numpy>=1.26.4",
    "openpyxl>=3.1.5",
    "pandas>=2.2.2",
    "patito>=0.6.1",
    "plotly>=5.22.0",
    "polarify>=0.2.0",
    "polars-ds>=0.4.4",
    "polars>=0.20.31",
    "polugins>=0.5.1",
    "pyarrow>=16.1.0",
    "pymc>=5.16.1",
    "pyper>=1.1.2",
    "pystan>=3.10.0",
    "python-lsp-ruff>=2.2.1",
    "python-lsp-server>=1.11.0",
    "ruff-lsp>=0.0.54",
    "ruff>=0.5.0",
    "scikit-learn>=1.5.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "shirokumas>=0.0.3",
    "statsmodels>=0.14.2",
    "sympy>=1.12.1",
    "tensorflow>=2.16.2",
    "torch>=2.3.1",
    "unidic-lite>=1.0.8",
    "xarray>=2024.6.0",
    "yfinance>=0.2.40",
]

[project.scripts]
hello = "workspace:playground"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/workspace"]
