[project]
name = "playground"
version = "0.1.0"
description = "Playground"
authors = [{ name = "Shoichieo Odaka", email = "odakas1994@gmail.com" }]
readme = "README.md"
requires-python = ">= 3.12"
dependencies = [
    "black>=24.4.0",
    "functime>=0.9.5",
    "ipyvuetable>=0.3.0",
    "jupyter>=1.0.0",
    "jupyterlab-code-formatter>=2.2.1",
    "jupyterlab-language-pack-ja-jp>=4.1.post2",
    "jupyterlab-lsp>=5.1.0",
    "lightgbm>=4.3.0",
    "matplotlib-fontja>=1.0.0",
    "matplotlib>=3.8.4",
    "mecab-python3>=1.0.8",
    "notebook>=7.1.2",
    "numpy>=1.26.4",
    "openpyxl>=3.1.2",
    "pandas==2.2.2",
    "patito>=0.6.1",
    "plotly>=5.20.0",
    "polarify>=0.1.5",
    "polars-ds>=0.4.1",
    "polars>=0.20.20",
    "polugins>=0.5.1",
    "pyarrow>=15.0.2",
    "pyper>=1.1.2",
    "python-lsp-ruff>=2.2.0",
    "python-lsp-server>=1.11.0",
    "ruff-lsp>=0.0.53",
    "ruff>=0.3.4",
    "scikit-learn>=1.4.2",
    "scipy>=1.13.0",
    "seaborn>=0.13.2",
    "shirokumas>=0.0.3",
    "statsmodels>=0.14.1",
    "sympy>=1.12",
    "tensorflow>=2.16.1",
    "torch>=2.2.2",
    "unidic-lite>=1.0.8",
    "xarray>=2024.3.0",
]

[project.scripts]
hello = "workspace:playground"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/workspace"]
